# -*- encoding=utf8 -*-
__author__ = "Adan"
icashPay_Android_version = "3.0.1.471049"

from airtest.core.api import *

auto_setup(__file__)
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
import time

poco("tw.com.icash.a.icashpay.debuging:id/personal_text").click()
poco(text="設定").click()
poco(text="變更登入密碼").click()
poco("tw.com.icash.a.icashpay.debuging:id/oldPwdText").click()
poco("tw.com.icash.a.icashpay.debuging:id/oldPwdText").set_text("Aa123456")
poco("tw.com.icash.a.icashpay.debuging:id/newPwdText").click()
poco("tw.com.icash.a.icashpay.debuging:id/newPwdText").set_text("Aa567890")
poco("tw.com.icash.a.icashpay.debuging:id/doubleNewPwdText").click()
poco("tw.com.icash.a.icashpay.debuging:id/doubleNewPwdText").set_text("Aa567890")
poco("com.android.systemui:id/back").click()
poco("tw.com.icash.a.icashpay.debuging:id/leftButton").click()
poco("tw.com.icash.a.icashpay.debuging:id/txt_right").click()
poco(text="變更登入密碼").click()
poco("tw.com.icash.a.icashpay.debuging:id/oldPwdText").click()
poco("tw.com.icash.a.icashpay.debuging:id/oldPwdText").set_text("Aa567890")
poco("tw.com.icash.a.icashpay.debuging:id/newPwdText").click()
poco("tw.com.icash.a.icashpay.debuging:id/newPwdText").set_text("Aa123456")
poco("tw.com.icash.a.icashpay.debuging:id/doubleNewPwdText").click()
poco("tw.com.icash.a.icashpay.debuging:id/doubleNewPwdText").set_text("Aa123456")
poco("com.android.systemui:id/back").click()
poco("tw.com.icash.a.icashpay.debuging:id/leftButton").click()
poco("tw.com.icash.a.icashpay.debuging:id/txt_right").click()
poco(text="變更安全密碼").click()
poco(text="2").click()
poco(text="4").click()
poco(text="6").click()
poco(text="7").click()
poco(text="9").click()
poco(text="0").click()
touch(Template(r"tpl1729842436337.png", record_pos=(-0.305, -0.344), resolution=(1080, 2400)))

poco(text="1").click()
poco(text="3").click()
poco(text="5").click()
poco(text="7").click()
poco(text="9").click()
poco(text="0").click()
touch(Template(r"tpl1729842934026.png", record_pos=(-0.305, 0.058), resolution=(1080, 2400)))
poco(text="1").click()
poco(text="3").click()
poco(text="5").click()
poco(text="7").click()
poco(text="9").click()
poco(text="0").click()
poco("tw.com.icash.a.icashpay.debuging:id/tvConfirm").click()
poco("tw.com.icash.a.icashpay.debuging:id/txt_right").click()
poco(text="變更安全密碼").click()
poco("tw.com.icash.a.icashpay.debuging:id/pin1").click()
poco(text="1").click()
poco(text="3").swipe([-0.0037, 0.0])
poco(text="5").click()
poco(text="7").click()
poco(text="9").click()
poco(text="0").click()
touch(Template(r"tpl1729843421921.png", record_pos=(-0.305, -0.348), resolution=(1080, 2400)))
poco(text="2").click()
poco(text="4").click()
poco(text="6").click()
poco(text="7").click()
poco(text="9").click()
poco(text="0").click()
touch(Template(r"tpl1729843454488.png", record_pos=(-0.305, 0.047), resolution=(1080, 2400)))
poco(text="2").click()
poco(text="4").click()
poco(text="6").click()
poco(text="7").click()
poco(text="9").click()
poco(text="0").click()
poco("tw.com.icash.a.icashpay.debuging:id/tvConfirm").click()
poco("tw.com.icash.a.icashpay.debuging:id/txt_right").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
poco("tw.com.icash.a.icashpay.debuging:id/text").click()
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/base_container").offspring("tw.com.icash.a.icashpay.debuging:id/nav").offspring("android.widget.ImageView").click()
poco("tw.com.icash.a.icashpay.debuging:id/text").click()
