# -*- encoding=utf8 -*-
__author__ = "Adan"

from airtest.core.api import *

auto_setup(__file__)


#from poco.drivers.ios import iosPoco
#poco = iosPoco()
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
#poco("tw.com.icash.a.icashpay.debuging:id/action").click()
#sleep(1.0)
#poco("tw.com.icash.a.icashpay.debuging:id/et_acct").click()
#poco("tw.com.icash.a.icashpay.debuging:id/et_acct").set_text("tester349")
#sleep(1.0)
#poco("tw.com.icash.a.icashpay.debuging:id/et_pwd").click()
#poco("tw.com.icash.a.icashpay.debuging:id/et_pwd").set_text("Aa123456")
#poco("tw.com.icash.a.icashpay.debuging:id/bt_login").click()
poco(text="儲值").click()
sleep(2.0)
poco(text="現金儲值").click()
poco("tw.com.icash.a.icashpay.debuging:id/add_100").click()
poco("tw.com.icash.a.icashpay.debuging:id/text").click()
poco("tw.com.icash.a.icashpay.debuging:id/title_left").click()
poco("tw.com.icash.a.icashpay.debuging:id/title_right").click()
poco(text="自帶杯儲值").click()
sleep(1.0)
poco("tw.com.icash.a.icashpay.debuging:id/close").click()
poco(text="中獎發票儲值").click()
sleep(1.0)
poco("tw.com.icash.a.icashpay.debuging:id/close").click()
poco("tw.com.icash.a.icashpay.debuging:id/title_right").click()
poco("tw.com.icash.a.icashpay.debuging:id/fund").click()
poco("tw.com.icash.a.icashpay.debuging:id/loan").click()
poco("tw.com.icash.a.icashpay.debuging:id/personal").click()
poco(text="交易限額").click()
sleep(1.0)
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
poco("tw.com.icash.a.icashpay.debuging:id/lvSetting").click()
sleep(1.0)
poco(text="授權扣款管理").click()
sleep(1.0)
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(1.0)
poco(text="使用教學").click()
sleep(1.0)
#poco(text="確定前往").click()
#("com.android.systemui:id/back").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
poco(text="版本與登入紀錄").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(1.0)
poco(text="常見問題").click()
#poco(text="確定前往").click()
#poco("com.android.systemui:id/back").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(1.0)
poco(text="服務條款").click()
#poco(text="確定前往").click()
#poco("com.android.systemui:id/back").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
poco('Scpoco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/base_container").offspring("tw.com.icash.a.icashpay.debuging:id/fragment_container").offspring("tw.com.icash.a.icashpay.debuging:id/content_container").offspring("tw.com.icash.a.icashpay.debuging:id/lvInformation").child("android.widget.LinearLayout")[1]')
swipe(Template(r"tpl1728959653556.png", record_pos=(0.043, 0.643), resolution=(1080, 2400)), vector=[0.1086, -0.2909])

poco(text="聯絡我們").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(2.0)
poco("tw.com.icash.a.icashpay.debuging:id/nav").click()

poco("tw.com.icash.a.icashpay.debuging:id/home_text").click()
poco("tw.com.icash.a.icashpay.debuging:id/text").click()
poco(text="2").click()
poco(text="4").click()
poco(text="6").click()
poco(text="7").click()
poco(text="9").click()
poco(text="0").click()
sleep(2.0)
poco("tw.com.icash.a.icashpay.debuging:id/payment_qrcode").click()
poco("tw.com.icash.a.icashpay.debuging:id/invoice_image").click()
poco("tw.com.icash.a.icashpay.debuging:id/member_image").click()
poco("tw.com.icash.a.icashpay.debuging:id/all_image").click()
poco("tw.com.icash.a.icashpay.debuging:id/close").click()
sleep(1.0)
poco(text="生活服務").click()
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/base_container").offspring("tw.com.icash.a.icashpay.debuging:id/fragment_container").offspring("tw.com.icash.a.icashpay.debuging:id/scroll_view").offspring("tw.com.icash.a.icashpay.debuging:id/home_container").child("android.widget.LinearLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/function_service").offspring("tw.com.icash.a.icashpay.debuging:id/invoice").child("android.widget.ImageView").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/base_container").offspring("tw.com.icash.a.icashpay.debuging:id/fragment_container").offspring("tw.com.icash.a.icashpay.debuging:id/scroll_view").offspring("tw.com.icash.a.icashpay.debuging:id/home_container").child("android.widget.LinearLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/function_service").offspring("tw.com.icash.a.icashpay.debuging:id/bus_code").child("android.widget.ImageView").click()
poco("tw.com.icash.a.icashpay.debuging:id/text").click()
poco(text="2").click()
poco(text="4").click()
poco(text="6").click()
poco(text="7").click()
poco(text="9").click()
poco(text="0").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
#icash 2.0
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/base_container").offspring("tw.com.icash.a.icashpay.debuging:id/fragment_container").offspring("tw.com.icash.a.icashpay.debuging:id/scroll_view").offspring("tw.com.icash.a.icashpay.debuging:id/home_container").child("android.widget.LinearLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/function_service").offspring("tw.com.icash.a.icashpay.debuging:id/icash").child("android.widget.ImageView").click()
sleep(1.0)
# 新卡上市
poco(text="新卡上市").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").swipe([0.0, -0.0017])
#icash2.0記名
#poco(text="確定前往").click()
#poco("com.android.systemui:id/back").click()
#poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
#icash2.0記名
poco(text="icash2.0記名").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()


#活動快訊
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/rv_card_entrance").child("tw.com.icash.a.icashpay.debuging:id/cv_card_entrance")[2].offspring("tw.com.icash.a.icashpay.debuging:id/img_card_entrance_icon").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
#聯名卡優惠
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/rv_card_entrance").child("tw.com.icash.a.icashpay.debuging:id/cv_card_entrance")[3].offspring("tw.com.icash.a.icashpay.debuging:id/img_card_entrance_icon").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
#使用通路
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/rv_card_entrance").child("tw.com.icash.a.icashpay.debuging:id/cv_card_entrance")[4].offspring("tw.com.icash.a.icashpay.debuging:id/img_card_entrance_icon").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
#掛失服務
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/rv_card_entrance").child("tw.com.icash.a.icashpay.debuging:id/cv_card_entrance")[4].offspring("tw.com.icash.a.icashpay.debuging:id/img_card_entrance_icon").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
#NFC查詢
poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/rv_card_entrance").child("tw.com.icash.a.icashpay.debuging:id/cv_card_entrance")[6].offspring("tw.com.icash.a.icashpay.debuging:id/img_card_entrance_icon").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
#生活優惠
swipe(Template(r"tpl1728960301469.png", record_pos=(0.162, 0.11), resolution=(1080, 2400)), vector=[-0.045, -0.1168])

poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/base_container").offspring("tw.com.icash.a.icashpay.debuging:id/fragment_container").offspring("tw.com.icash.a.icashpay.debuging:id/scroll_view").offspring("tw.com.icash.a.icashpay.debuging:id/home_container").offspring("tw.com.icash.a.icashpay.debuging:id/coop_more").child("android.widget.TextView").click()
poco("tw.com.icash.a.icashpay.debuging:id/title_left").click()
#銀行優惠
swipe(Template(r"tpl1728960640515.png", record_pos=(0.197, -0.083), resolution=(1080, 2400)), vector=[0.0106, -0.2408])

poco("android.widget.FrameLayout").child("android.widget.LinearLayout").offspring("tw.com.icash.a.icashpay.debuging:id/base_container").offspring("tw.com.icash.a.icashpay.debuging:id/fragment_container").offspring("tw.com.icash.a.icashpay.debuging:id/scroll_view").offspring("tw.com.icash.a.icashpay.debuging:id/home_container").offspring("tw.com.icash.a.icashpay.debuging:id/cash_bank_container").offspring("tw.com.icash.a.icashpay.debuging:id/cashback_more").child("android.widget.TextView").click()
poco("tw.com.icash.a.icashpay.debuging:id/text").click()
poco(text="確定前往").click()
poco("com.android.systemui:id/back").click()
poco("tw.com.icash.a.icashpay.debuging:id/base_title").click()
poco("tw.com.icash.a.icashpay.debuging:id/title_left").swipe([0.0, -0.0017])